// Generated by gencpp from file unr_deepspeech/Listen.msg
// DO NOT EDIT!


#ifndef UNR_DEEPSPEECH_MESSAGE_LISTEN_H
#define UNR_DEEPSPEECH_MESSAGE_LISTEN_H

#include <ros/service_traits.h>


#include <unr_deepspeech/ListenRequest.h>
#include <unr_deepspeech/ListenResponse.h>


namespace unr_deepspeech
{

struct Listen
{

typedef ListenRequest Request;
typedef ListenResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Listen
} // namespace unr_deepspeech


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::unr_deepspeech::Listen > {
  static const char* value()
  {
    return "d3b16d8cd85e65cb9eefd2c2099a8d05";
  }

  static const char* value(const ::unr_deepspeech::Listen&) { return value(); }
};

template<>
struct DataType< ::unr_deepspeech::Listen > {
  static const char* value()
  {
    return "unr_deepspeech/Listen";
  }

  static const char* value(const ::unr_deepspeech::Listen&) { return value(); }
};


// service_traits::MD5Sum< ::unr_deepspeech::ListenRequest> should match
// service_traits::MD5Sum< ::unr_deepspeech::Listen >
template<>
struct MD5Sum< ::unr_deepspeech::ListenRequest>
{
  static const char* value()
  {
    return MD5Sum< ::unr_deepspeech::Listen >::value();
  }
  static const char* value(const ::unr_deepspeech::ListenRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::unr_deepspeech::ListenRequest> should match
// service_traits::DataType< ::unr_deepspeech::Listen >
template<>
struct DataType< ::unr_deepspeech::ListenRequest>
{
  static const char* value()
  {
    return DataType< ::unr_deepspeech::Listen >::value();
  }
  static const char* value(const ::unr_deepspeech::ListenRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::unr_deepspeech::ListenResponse> should match
// service_traits::MD5Sum< ::unr_deepspeech::Listen >
template<>
struct MD5Sum< ::unr_deepspeech::ListenResponse>
{
  static const char* value()
  {
    return MD5Sum< ::unr_deepspeech::Listen >::value();
  }
  static const char* value(const ::unr_deepspeech::ListenResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::unr_deepspeech::ListenResponse> should match
// service_traits::DataType< ::unr_deepspeech::Listen >
template<>
struct DataType< ::unr_deepspeech::ListenResponse>
{
  static const char* value()
  {
    return DataType< ::unr_deepspeech::Listen >::value();
  }
  static const char* value(const ::unr_deepspeech::ListenResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNR_DEEPSPEECH_MESSAGE_LISTEN_H
