// Generated by gencpp from file unr_deepspeech/ListenRequest.msg
// DO NOT EDIT!


#ifndef UNR_DEEPSPEECH_MESSAGE_LISTENREQUEST_H
#define UNR_DEEPSPEECH_MESSAGE_LISTENREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unr_deepspeech
{
template <class ContainerAllocator>
struct ListenRequest_
{
  typedef ListenRequest_<ContainerAllocator> Type;

  ListenRequest_()
    : filename()  {
    }
  ListenRequest_(const ContainerAllocator& _alloc)
    : filename(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filename_type;
  _filename_type filename;





  typedef boost::shared_ptr< ::unr_deepspeech::ListenRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unr_deepspeech::ListenRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ListenRequest_

typedef ::unr_deepspeech::ListenRequest_<std::allocator<void> > ListenRequest;

typedef boost::shared_ptr< ::unr_deepspeech::ListenRequest > ListenRequestPtr;
typedef boost::shared_ptr< ::unr_deepspeech::ListenRequest const> ListenRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unr_deepspeech::ListenRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unr_deepspeech::ListenRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::unr_deepspeech::ListenRequest_<ContainerAllocator1> & lhs, const ::unr_deepspeech::ListenRequest_<ContainerAllocator2> & rhs)
{
  return lhs.filename == rhs.filename;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::unr_deepspeech::ListenRequest_<ContainerAllocator1> & lhs, const ::unr_deepspeech::ListenRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace unr_deepspeech

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::unr_deepspeech::ListenRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unr_deepspeech::ListenRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unr_deepspeech::ListenRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unr_deepspeech::ListenRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unr_deepspeech::ListenRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unr_deepspeech::ListenRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unr_deepspeech::ListenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::unr_deepspeech::ListenRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x030824f52a0628eaULL;
  static const uint64_t static_value2 = 0xd956fb9d67e66ae9ULL;
};

template<class ContainerAllocator>
struct DataType< ::unr_deepspeech::ListenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unr_deepspeech/ListenRequest";
  }

  static const char* value(const ::unr_deepspeech::ListenRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unr_deepspeech::ListenRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string filename\n"
;
  }

  static const char* value(const ::unr_deepspeech::ListenRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unr_deepspeech::ListenRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListenRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unr_deepspeech::ListenRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unr_deepspeech::ListenRequest_<ContainerAllocator>& v)
  {
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNR_DEEPSPEECH_MESSAGE_LISTENREQUEST_H
