// Generated by gencpp from file unr_deepspeech/ListenResponse.msg
// DO NOT EDIT!


#ifndef UNR_DEEPSPEECH_MESSAGE_LISTENRESPONSE_H
#define UNR_DEEPSPEECH_MESSAGE_LISTENRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unr_deepspeech
{
template <class ContainerAllocator>
struct ListenResponse_
{
  typedef ListenResponse_<ContainerAllocator> Type;

  ListenResponse_()
    : prediction()  {
    }
  ListenResponse_(const ContainerAllocator& _alloc)
    : prediction(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _prediction_type;
  _prediction_type prediction;





  typedef boost::shared_ptr< ::unr_deepspeech::ListenResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unr_deepspeech::ListenResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ListenResponse_

typedef ::unr_deepspeech::ListenResponse_<std::allocator<void> > ListenResponse;

typedef boost::shared_ptr< ::unr_deepspeech::ListenResponse > ListenResponsePtr;
typedef boost::shared_ptr< ::unr_deepspeech::ListenResponse const> ListenResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unr_deepspeech::ListenResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unr_deepspeech::ListenResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::unr_deepspeech::ListenResponse_<ContainerAllocator1> & lhs, const ::unr_deepspeech::ListenResponse_<ContainerAllocator2> & rhs)
{
  return lhs.prediction == rhs.prediction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::unr_deepspeech::ListenResponse_<ContainerAllocator1> & lhs, const ::unr_deepspeech::ListenResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace unr_deepspeech

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::unr_deepspeech::ListenResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unr_deepspeech::ListenResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unr_deepspeech::ListenResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unr_deepspeech::ListenResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unr_deepspeech::ListenResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unr_deepspeech::ListenResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unr_deepspeech::ListenResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44a298085da4e117b1416bb683e65e00";
  }

  static const char* value(const ::unr_deepspeech::ListenResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44a298085da4e117ULL;
  static const uint64_t static_value2 = 0xb1416bb683e65e00ULL;
};

template<class ContainerAllocator>
struct DataType< ::unr_deepspeech::ListenResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unr_deepspeech/ListenResponse";
  }

  static const char* value(const ::unr_deepspeech::ListenResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unr_deepspeech::ListenResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string prediction\n"
;
  }

  static const char* value(const ::unr_deepspeech::ListenResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unr_deepspeech::ListenResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.prediction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListenResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unr_deepspeech::ListenResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unr_deepspeech::ListenResponse_<ContainerAllocator>& v)
  {
    s << indent << "prediction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.prediction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNR_DEEPSPEECH_MESSAGE_LISTENRESPONSE_H
