// Generated by gencpp from file manipulation/ReturnJointStatesRequest.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MESSAGE_RETURNJOINTSTATESREQUEST_H
#define MANIPULATION_MESSAGE_RETURNJOINTSTATESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulation
{
template <class ContainerAllocator>
struct ReturnJointStatesRequest_
{
  typedef ReturnJointStatesRequest_<ContainerAllocator> Type;

  ReturnJointStatesRequest_()
    : name()  {
    }
  ReturnJointStatesRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReturnJointStatesRequest_

typedef ::manipulation::ReturnJointStatesRequest_<std::allocator<void> > ReturnJointStatesRequest;

typedef boost::shared_ptr< ::manipulation::ReturnJointStatesRequest > ReturnJointStatesRequestPtr;
typedef boost::shared_ptr< ::manipulation::ReturnJointStatesRequest const> ReturnJointStatesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manipulation::ReturnJointStatesRequest_<ContainerAllocator1> & lhs, const ::manipulation::ReturnJointStatesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manipulation::ReturnJointStatesRequest_<ContainerAllocator1> & lhs, const ::manipulation::ReturnJointStatesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manipulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f2d21c30868b92dc41a0431bacd47b2";
  }

  static const char* value(const ::manipulation::ReturnJointStatesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f2d21c30868b92dULL;
  static const uint64_t static_value2 = 0xc41a0431bacd47b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulation/ReturnJointStatesRequest";
  }

  static const char* value(const ::manipulation::ReturnJointStatesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] name\n"
;
  }

  static const char* value(const ::manipulation::ReturnJointStatesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReturnJointStatesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulation::ReturnJointStatesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulation::ReturnJointStatesRequest_<ContainerAllocator>& v)
  {
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATION_MESSAGE_RETURNJOINTSTATESREQUEST_H
